import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:material_ui_migration/app/app.dart';

/// The referee for this whole experiment.
///
/// Two kinds of string live in this app, and the migration treats them
/// differently:
///
/// * ours, generated by gen-l10n from lib/l10n/*.arb;
/// * Material's and Cupertino's own, which move out of flutter_localizations
///   and into material_ui / cupertino_ui.
///
/// A real app broke on exactly this: it registered only its generated
/// delegates after migrating, so every non-English locale fell back to
/// English and a TextField crashed with a null check error in release mode.
/// See https://github.com/TomBursch/kitchenowl/pull/1164.
///
/// These tests pass before the migration. If they still pass after it, the
/// localization part of the migration is done. If they fail, the article has
/// its answer.
void main() {
  testWidgets('French: our own generated strings resolve', (
    WidgetTester tester,
  ) async {
    await tester.pumpWidget(const ResidenceApp(initialLocale: Locale('fr')));
    await tester.pumpAndSettle();

    expect(find.text('Tableau de bord'), findsOneWidget);
    expect(find.text('Rechercher un résident'), findsOneWidget);

    // The plural and the date are the interesting ones: their shape comes
    // from the locale, not from a lookup table.
    expect(find.text('42 résidents'), findsOneWidget);
    expect(find.text('Dernière synchronisation : 3 octobre 2026'), findsOneWidget);
  });

  testWidgets('French: Material and Cupertino strings resolve too', (
    WidgetTester tester,
  ) async {
    await tester.pumpWidget(const ResidenceApp(initialLocale: Locale('fr')));
    await tester.pumpAndSettle();

    final BuildContext context = tester.element(
      find.byKey(const Key('search-field')),
    );

    final MaterialLocalizations material = MaterialLocalizations.of(context);
    expect(material.closeButtonLabel, isNot('Close'));
    expect(material.closeButtonLabel, 'Fermer');

    final CupertinoLocalizations cupertino = CupertinoLocalizations.of(context);
    expect(cupertino.alertDialogLabel, isNot('Alert'));
  });

  testWidgets('English stays English', (WidgetTester tester) async {
    await tester.pumpWidget(const ResidenceApp());
    await tester.pumpAndSettle();

    final BuildContext context = tester.element(
      find.byKey(const Key('search-field')),
    );

    expect(MaterialLocalizations.of(context).closeButtonLabel, 'Close');
    expect(CupertinoLocalizations.of(context).alertDialogLabel, 'Alert');
  });
}
